
USE  MAGAZIN
GO


--  Chei  straine  in  tabela  PRODUS
ALTER  TABLE  PRODUS
        ADD  CONSTRAINT  FK_PRODUS_FURNIZOR  FOREIGN  KEY  (Id_Furnizor) 
REFERENCES  FURNIZOR(Id_Furnizor);
GO

ALTER  TABLE  PRODUS
        ADD  CONSTRAINT  FK_PRODUS_CATEGORIE  FOREIGN  KEY  (Id_Categorie) 
REFERENCES  CATEGORIE(Id_Categorie);
GO


--  Chei  straine  in  tabela  DETALII_COMANDA
ALTER  TABLE  DETALII_COMANDA
        ADD  CONSTRAINT  FK_DETALII_COMANDA_COMANDA  FOREIGN  KEY  (Id_Comanda) 
REFERENCES  COMANDA(Id_Comanda);
GO

ALTER  TABLE  DETALII_COMANDA
        ADD  CONSTRAINT  FK_DETALII_COMANDA_PRODUS  FOREIGN  KEY  (Id_Produs) 
REFERENCES  PRODUS(Id_Produs);
GO



--  Chei  straine  in  tabela  COMANDA
ALTER  TABLE  COMANDA
        ADD  CONSTRAINT  FK_COMANDA_PLATA  FOREIGN  KEY  (Id_Plata) 
REFERENCES  PLATA(Id_Plata);
GO

ALTER  TABLE  COMANDA
        ADD  CONSTRAINT  FK_COMANDA_CLIENT  FOREIGN  KEY  (Id_Client) 
REFERENCES  CLIENT(Id_Client);
GO

ALTER  TABLE  COMANDA
        ADD  CONSTRAINT  FK_COMANDA_EXPEDITOR  FOREIGN  KEY  (Id_Expeditor) 
REFERENCES  EXPEDITOR(Id_Expeditor);
GO
